### ISSUE TITLE
[BUG] cannot load such file -- rss/1.0

### ISSUE THREAD

**Issue by agramichael** [opensearch-project/opensearch-ruby#30]
**What is the bug?**
`rss` isn't declared as a dependency so isn't automatically installed.
Adding `rss` to my gemfile solved it.

**How can one reproduce the bug?**
1. Add opensearch to gemfile
2. Bunde install
3. Try running the server

**What is your host/environment?**
 - OS: macOS Monterey
 - Version: 12.0.1

**Do you have any additional context?**
```
/Users/michael/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- rss/1.0 (LoadError)
        from /Users/michael/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /Users/michael/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
        from /Users/michael/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /Users/michael/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require'
        from /Users/michael/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
        from /Users/michael/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /Users/michael/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        from /Users/michael/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/opensearch-0.0.1/lib/opensearch/base.rb:4:in `<main>'
```

**Comment by jayeshathila** [comment]
Hi, We haven't yet released the GEM.  
You can track the Gem publishing [here](https://github.com/opensearch-project/opensearch-ruby/issues/23)

**Comment by jayeshathila** [comment]
We published the Gem yesterday, you can find it [here](https://rubygems.org/gems/opensearch-ruby) 
Closing this issue as of now. Please reopen if you find any issue.
